mqtt:
  sensor:
    - name: "MPPT auth"
      state_topic: "vedirect2mqtt/mppt/auth"
      unique_id: "mppt_auth"
      
    - name: "MPPT Panel power"
      state_topic: "vedirect2mqtt/mppt/PPV"
      unique_id: "mppt_PPV"
      unit_of_measurement: "W"
      device_class: power

    - name: "MPPT Panel voltage"
      state_topic: "vedirect2mqtt/mppt/VPV"
      unique_id: "mppt_VPV"
      unit_of_measurement: "V"
      device_class: voltage
      value_template: '{{ value | int / 1000 }}'

    - name: "MPPT Battery voltage"
      state_topic: "vedirect2mqtt/mppt/V"
      unique_id: "mppt_V"
      unit_of_measurement: "V"
      device_class: voltage
      value_template: '{{ value | int / 1000 }}'
      
    - name: "MPPT Battery current"
      state_topic: "vedirect2mqtt/mppt/I"
      unique_id: "mppt_I"
      unit_of_measurement: "A"
      device_class: current
      value_template: '{{ value | int / 1000 }}'
  
    - name: "MPPT Load current"
      state_topic: "vedirect2mqtt/mppt/IL"
      unique_id: "mppt_IL"
      unit_of_measurement: "A"
      device_class: current
      value_template: '{{ value | int / 1000 }}'
      
    - name: "MPPT State of operation"
      state_topic: "vedirect2mqtt/mppt/CS"
      unique_id: "mppt_CS"
      value_template: >-
        {% if value == '0' %} "Off"
        {% elif value == '2' %} 'Fault'
        {% elif value == '3' %} 'Bulk'
        {% elif value == '4' %} 'Absorption'
        {% elif value == '5' %} 'Float'
        {% endif %}
      
    - name: "MPPT Tracker operation mode"
      state_topic: "vedirect2mqtt/mppt/MPPT"
      unique_id: "mppt_MPPT"
      value_template: >-
        {% if value == '0' %} "Off"
        {% elif value == '1' %} 'Voltage or current limited 1'
        {% elif value == '2' %} 'MPP Tracker active'
        {% endif %}
      
    - name: "MPPT Off reason"
      state_topic: "vedirect2mqtt/mppt/OR"
      unique_id: "mppt_OR"
      value_template: >-
        {% if value == '0x00000001' %} 'No input power'
        {% elif value == '0x00000002' %} 'Switched off (power switch)'
        {% elif value == '0x00000004' %} 'Switched off (device mode register)'
        {% elif value == '0x00000008' %} 'Remote input'
        {% elif value == '0x00000010' %} 'Protection active'
        {% elif value == '0x00000020' %} 'Paygo'
        {% elif value == '0x00000040' %} 'BMS'
        {% elif value == '0x00000080' %} 'Engine shutdown detection'
        {% elif value == '0x00000100' %} 'Analysing input voltage'
        {% endif %}

    - name: "MPPT Error code"
      state_topic: "vedirect2mqtt/mppt/ERR"
      unique_id: "mppt_ERR"
      value_template: >-
        {% if value == '0' %} 'No Error'
        {% elif value == '2' %} 'Battery voltage too high'
        {% elif value == '17' %} 'Charger temperature too high'
        {% elif value == '18' %} 'Charger over current'
        {% elif value == '19' %} 'Charger current reversed'
        {% elif value == '20' %} 'Bulk time limit exceeded'
        {% elif value == '21' %} 'Current sensor issue (sensor bias/sensor broken)'
        {% elif value == '26' %} 'Terminals overheated'
        {% elif value == '28' %} 'Converter issue (dual converter models only)'
        {% elif value == '33' %} 'Input voltage too high (solar panel)'
        {% elif value == '34' %} 'Input current too high (solar panel)'
        {% elif value == '38' %} 'Input shutdown (due to excessive battery voltage)'
        {% elif value == '39' %} 'Input shutdown (due to current flow during off mode)'
        {% elif value == '65' %} 'Lost communication with one of devices'
        {% elif value == '66' %} 'Synchronised charging device configuration issue'
        {% elif value == '67' %} 'BMS connection lost'
        {% elif value == '68' %} 'Network misconfigured'
        {% elif value == '116' %} 'Factory calibration data lost'
        {% elif value == '117' %} 'Invalid/incompatible firmware'
        {% elif value == '119' %} 'ser settings invalid'
        {% endif %}

    - name: "MPPT Yield total (user resettable counter)"
      state_topic: "vedirect2mqtt/mppt/H19"
      unique_id: "mppt_H19"
      unit_of_measurement: "Wh"
      device_class: energy
      value_template: '{{ value | int * 10 }}'

    - name: "MPPT Yield today"
      state_topic: "vedirect2mqtt/mppt/H20"
      unique_id: "mppt_H20"
      unit_of_measurement: "Wh"
      device_class: energy
      state_class: total
      value_template: '{{ value | int * 10 }}'

    - name: "MPPT Maximum power today"
      state_topic: "vedirect2mqtt/mppt/H21"
      unique_id: "mppt_H21"
      unit_of_measurement: "W"
      device_class: power

    - name: "MPPT Yield yesterday"
      state_topic: "vedirect2mqtt/mppt/H22"
      unique_id: "mppt_H22"
      unit_of_measurement: "Wh"
      device_class: energy
      state_class: total
      value_template: '{{ value | int * 10 }}'

    - name: "MPPT Maximum power yesterday"
      state_topic: "vedirect2mqtt/mppt/H23"
      unique_id: "mppt_H23"
      unit_of_measurement: "W"
      device_class: power